---
title: "helloworld"
date: 2018-12-25
---

title: Leonard's Portfolio
author: GitHub User
email: leonard@opswerks.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle
github_username:  @leonardrae

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
